### ISSUE TITLE
You can't install the app on your device.

### ISSUE THREAD

**Issue by Shadow00Caster** [rick51231/unifi-protect-android-direct#2]
This is amazing first off, thank you.

Trying to install on Pixel 6 Pro running stock Android 12, see screenshot below.  Any ideas?

![Screenshot_20211224-161939](https://user-images.githubusercontent.com/13611109/147374794-175f2a64-f789-462a-ab6b-f60f0636c1b1.png)
.

**Comment by GekoCH** [comment]
I have the same Problem, it says "App not installed" after launching the APK File...

**Comment by rick51231** [comment]
Hello. Sorry for the late answer...

In the latest version i used a new signing method so it should work now.

**Comment by GekoCH** [comment]
thx 
so the patches for 1.4.7 do work however I had to change the `apksinger `to `java -jar /usr/bin/apksigner` to get the build_apk.sh working

for the 1.10.1 some patches fail:
```
root@lms:~/unifi-protect-android-direct# patch out/smali_classes*/com/ubnt/common/service/discovery/DiscoveryService.smali wifi.patch
patching file out/smali_classes3/com/ubnt/common/service/discovery/DiscoveryService.smali
Hunk #1 FAILED at 740.
1 out of 1 hunk FAILED -- saving rejects to file out/smali_classes3/com/ubnt/common/service/discovery/DiscoveryService.smali.rej
root@lms:~/unifi-protect-android-direct# patch out/smali_classes*/com/ubnt/common/service/discovery/DiscoveryService.smali direct_connection.patch
patching file out/smali_classes3/com/ubnt/common/service/discovery/DiscoveryService.smali
Hunk #1 FAILED at 803.
Hunk #2 succeeded at 1360 with fuzz 1 (offset 535 lines).
1 out of 2 hunks FAILED -- saving rejects to file out/smali_classes3/com/ubnt/common/service/discovery/DiscoveryService.smali.rej
```

and after that I can't build the apk...

**Comment by rick51231** [comment]
I've checked apksinger from SDK, it's just a bash file... Fixed in 660638238da961d7dfdcc3f25378776a8a155cc7

Where did you get 1.10.1 version? Mine is from apkmirror `com.ubnt.unifi.protect_1.10.1-318_minAPI24(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk`

**Comment by GekoCH** [comment]
I tested both the one from Apkpure and the one from apkmirror.
Will you provide a patched apk to be downloaded. 1.4.7 works ok but I rather like to upgrade to 1.10.1

**Comment by GekoCH** [comment]
Ok did another run at the 1.10.1 version. now the patches worked. but the built failed:

```
root@lms:~/unifi-protect-android-direct# ./build_apk.sh
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
Killed
Unable to open 'protect-patched-unsigned.apk' as zip archive
Exception in thread "main" java.io.FileNotFoundException: protect-patched-unsigned-aligned.apk (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:154)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:326)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
rm: cannot remove 'protect-patched-unsigned.apk': No such file or directory
mv: cannot stat 'protect-patched-unsigned-aligned.apk': No such file or directory

```

**Comment by rick51231** [comment]
Yesterday I somehow deleted all the tags and the releases went into drafts... Fixed.

**Comment by rick51231** [comment]
Build has also been fixed. Accidentally provided macOS version.

**Comment by GekoCH** [comment]
thx for the apk.
no when I built the new apk I get this error:
`tools/zipalign: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libc++.so: file too short`

any guess???

**Comment by GekoCH** [comment]
ok now it works

I had to use the installed zipalign tool rather then the one in the tools folder so with 
`zipalign -p 4 protect-patched-unsigned.apk protect-patched-unsigned-aligned.apk
`i was able to build and run the apk on my phone.

**Comment by rick51231** [comment]
My mistake that there is many distributions and bad idea to provide binary with necessary libs for all of them.

Finally removed zipalign from repo. It can be obtained via package manager (`apt-get install zipalign` for Debian/Ubuntu) or use [Android BuildTools](https://androidsdkmanager.azurewebsites.net/Buildtools)

**Comment by GekoCH** [comment]
yep thats much better thx a lot!

**Comment by rick51231** [comment]
Thx for the help :)
