### ISSUE TITLE
Problem with unifi-protect 1.10.1

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [rick51231/unifi-protect-android-direct#6]
Error in compiling:
```
[myhost]:~/opt/unifi-protect-android-direct$ ./build_apk.sh
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
chmod: impossibile accedere a 'tools/zipalign': File o directory non esistente
./build_apk.sh: riga 6: zipalign: comando non trovato
Exception in thread "main" java.io.FileNotFoundException: protect-patched-unsigned-aligned.apk (File o directory non esistente)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:154)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:326)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
mv: impossibile eseguire stat di 'protect-patched-unsigned-aligned.apk': File o directory non esistente
```

**Comment by rick51231** [comment]
Hello

You have an error "zipalign: comando non trovato" (google translated to "command not found"). Please check zipalign installation (`apt-get install zipalign` for Debian/Ubuntu)

**Comment by rardcode** [comment]
> 

I use Arch/Manjaro and there isn't zipalign.

**Comment by gianlucavagnuzzi** [comment]
> Hello
> 
> You have an error "zipalign: comando non trovato" (google translated to "command not found"). Please check zipalign installation (`apt-get install zipalign` for Debian/Ubuntu)


I use Arch/Manjaro and there isn't zipalign.
